//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportImportSystem.cwxxWsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cwxx.webservice.cwbb.syncsoft.com/", ConfigurationName="cwxxWsService.ICwxxWsService")]
    public interface ICwxxWsService {
        
        // CODEGEN: 命名空间 http://ws.syncsoft.com/ 的元素名称 wssbXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReportImportSystem.cwxxWsService.receiveXmlWebserviceResponse receiveXmlWebservice(ReportImportSystem.cwxxWsService.receiveXmlWebservice request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveXmlWebservice {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveXmlWebservice", Namespace="http://cwxx.webservice.cwbb.syncsoft.com/", Order=0)]
        public ReportImportSystem.cwxxWsService.receiveXmlWebserviceBody Body;
        
        public receiveXmlWebservice() {
        }
        
        public receiveXmlWebservice(ReportImportSystem.cwxxWsService.receiveXmlWebserviceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.syncsoft.com/")]
    public partial class receiveXmlWebserviceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wssbXml;
        
        public receiveXmlWebserviceBody() {
        }
        
        public receiveXmlWebserviceBody(string wssbXml) {
            this.wssbXml = wssbXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveXmlWebserviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveXmlWebserviceResponse", Namespace="http://cwxx.webservice.cwbb.syncsoft.com/", Order=0)]
        public ReportImportSystem.cwxxWsService.receiveXmlWebserviceResponseBody Body;
        
        public receiveXmlWebserviceResponse() {
        }
        
        public receiveXmlWebserviceResponse(ReportImportSystem.cwxxWsService.receiveXmlWebserviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class receiveXmlWebserviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public receiveXmlWebserviceResponseBody() {
        }
        
        public receiveXmlWebserviceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICwxxWsServiceChannel : ReportImportSystem.cwxxWsService.ICwxxWsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CwxxWsServiceClient : System.ServiceModel.ClientBase<ReportImportSystem.cwxxWsService.ICwxxWsService>, ReportImportSystem.cwxxWsService.ICwxxWsService {
        
        public CwxxWsServiceClient() {
        }
        
        public CwxxWsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CwxxWsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CwxxWsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CwxxWsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportImportSystem.cwxxWsService.receiveXmlWebserviceResponse ReportImportSystem.cwxxWsService.ICwxxWsService.receiveXmlWebservice(ReportImportSystem.cwxxWsService.receiveXmlWebservice request) {
            return base.Channel.receiveXmlWebservice(request);
        }
        
        public string receiveXmlWebservice(string wssbXml) {
            ReportImportSystem.cwxxWsService.receiveXmlWebservice inValue = new ReportImportSystem.cwxxWsService.receiveXmlWebservice();
            inValue.Body = new ReportImportSystem.cwxxWsService.receiveXmlWebserviceBody();
            inValue.Body.wssbXml = wssbXml;
            ReportImportSystem.cwxxWsService.receiveXmlWebserviceResponse retVal = ((ReportImportSystem.cwxxWsService.ICwxxWsService)(this)).receiveXmlWebservice(inValue);
            return retVal.Body.@return;
        }
    }
}
