//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportImportSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportImportSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;envelope&gt;&lt;header&gt;&lt;authen&gt;&lt;service&gt;100010&lt;/service&gt;&lt;nsrsbh&gt;admin&lt;/nsrsbh&gt;&lt;nsrmc&gt;nsrmc&lt;/nsrmc&gt;&lt;license&gt;123&lt;/license&gt;&lt;sequence&gt;c4ca4238a0b923820dcc509a6f75849b&lt;/sequence&gt;&lt;timestamp&gt;20111028153121100&lt;/timestamp&gt;&lt;/authen&gt;&lt;/header&gt;&lt;body&gt;&lt;logic&gt;&lt;czlx&gt;0&lt;/czlx&gt;&lt;sssq_q&gt;&lt;/sssq_q&gt;&lt;sssq_z&gt;&lt;/sssq_z&gt;&lt;cjbbxml&gt;&lt;?xml version=&quot;1.0&quot; encoding=&quot;GB2312&quot; standalone=&quot;yes&quot;?&gt;&lt;taxML xmlns=&quot;http://www.chinatax.gov.cn/dataspec/&quot;&gt;&lt;syxqyzcfzb&gt;&lt;nsrxxForm1&gt;&lt;nsrsbh&gt;&lt;/nsrsbh&gt;&lt;nsrmc&gt;&lt;/nsrmc&gt;&lt;bsrq&gt;YYYY-MM- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
